// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMyOV_Yn_okjhF4wvdHZUzu-WkH4FzD2Y',
    appId: '1:564070232586:web:a622c115cff927c9eea5f3',
    messagingSenderId: '564070232586',
    projectId: 'collabnotion-5b976',
    authDomain: 'collabnotion-5b976.firebaseapp.com',
    storageBucket: 'collabnotion-5b976.appspot.com',
    measurementId: 'G-EK0VC3LY8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkhdFkDZr607vGFKB6sM1DUQGBKXsJ0gY',
    appId: '1:564070232586:android:56dfac2b5def8b84eea5f3',
    messagingSenderId: '564070232586',
    projectId: 'collabnotion-5b976',
    storageBucket: 'collabnotion-5b976.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYMNvi20mFl8TSE3it7vV5-ScT9ox_aJY',
    appId: '1:564070232586:ios:25dc4a60bee7de44eea5f3',
    messagingSenderId: '564070232586',
    projectId: 'collabnotion-5b976',
    storageBucket: 'collabnotion-5b976.appspot.com',
    iosBundleId: 'com.example.collabNotionClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYMNvi20mFl8TSE3it7vV5-ScT9ox_aJY',
    appId: '1:564070232586:ios:25dc4a60bee7de44eea5f3',
    messagingSenderId: '564070232586',
    projectId: 'collabnotion-5b976',
    storageBucket: 'collabnotion-5b976.appspot.com',
    iosBundleId: 'com.example.collabNotionClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMyOV_Yn_okjhF4wvdHZUzu-WkH4FzD2Y',
    appId: '1:564070232586:web:45a97505f0cb0db2eea5f3',
    messagingSenderId: '564070232586',
    projectId: 'collabnotion-5b976',
    authDomain: 'collabnotion-5b976.firebaseapp.com',
    storageBucket: 'collabnotion-5b976.appspot.com',
    measurementId: 'G-X3PM3WB412',
  );
}
